/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GithubCard {
    'username': string;
  }
}

declare global {


  interface HTMLGithubCardElement extends Components.GithubCard, HTMLStencilElement {}
  var HTMLGithubCardElement: {
    prototype: HTMLGithubCardElement;
    new (): HTMLGithubCardElement;
  };
  interface HTMLElementTagNameMap {
    'github-card': HTMLGithubCardElement;
  }
}

declare namespace LocalJSX {
  interface GithubCard {
    'username'?: string;
  }

  interface IntrinsicElements {
    'github-card': GithubCard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'github-card': LocalJSX.GithubCard & JSXBase.HTMLAttributes<HTMLGithubCardElement>;
    }
  }
}


