/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GithubUserCard {
    /**
    * If true, this will display dummy data instead of fetching from the GitHub API
    */
    'testMode': boolean;
    /**
    * The username of the GitHub profile you want to display
    */
    'username': string;
  }
}

declare global {


  interface HTMLGithubUserCardElement extends Components.GithubUserCard, HTMLStencilElement {}
  var HTMLGithubUserCardElement: {
    prototype: HTMLGithubUserCardElement;
    new (): HTMLGithubUserCardElement;
  };
  interface HTMLElementTagNameMap {
    'github-user-card': HTMLGithubUserCardElement;
  }
}

declare namespace LocalJSX {
  interface GithubUserCard {
    /**
    * If true, this will display dummy data instead of fetching from the GitHub API
    */
    'testMode'?: boolean;
    /**
    * The username of the GitHub profile you want to display
    */
    'username'?: string;
  }

  interface IntrinsicElements {
    'github-user-card': GithubUserCard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'github-user-card': LocalJSX.GithubUserCard & JSXBase.HTMLAttributes<HTMLGithubUserCardElement>;
    }
  }
}


